name: Daily AHR Execution

on:
  schedule:
    - cron: '30 00 * * *'   # 每天 UTC 00:30（北京时间 08:30）
  workflow_dispatch: {}     # 支持手动触发

jobs:
  run-ahr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install pandas numpy scikit-learn requests jq

      - name: Test KuCoin API
        id: test-kucoin
        run: |
          echo "Testing KuCoin API..."
          API_URL="https://api.kucoin.com/api/v1/market/candles?type=1day&symbol=BNB-USDT&startAt=1609459200&endAt=1661990400"
          
          # 获取响应状态码和内容
          RESPONSE=$(curl -s -w "\n%{http_code}" "$API_URL")
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          RESPONSE_BODY=$(echo "$RESPONSE" | sed '$d')
          
          echo "HTTP Status Code: $HTTP_CODE"
          echo "Response Body:"
          echo "$RESPONSE_BODY" | jq . 2>/dev/null || echo "$RESPONSE_BODY"
          
          if [ "$HTTP_CODE" -eq 200 ]; then
            echo "::notice::KuCoin API 可用"
            echo "API_AVAILABLE=true" >> $GITHUB_ENV
          else
            echo "::error::KuCoin API 不可用"
            echo "API_AVAILABLE=false" >> $GITHUB_ENV
            # 显示可能的原因
            if echo "$RESPONSE_BODY" | grep -q "Too Many Requests"; then
              echo "原因: 请求频率过高"
            elif echo "$RESPONSE_BODY" | grep -q "Invalid symbol"; then
              echo "原因: 交易对符号错误"
            fi
            exit 1  # 立即失败
          fi

      - name: Run AHR Script (if API available)
        if: env.API_AVAILABLE == 'true'
        run: |
          cd app/dashboard/python
          python ahr.py --api kucoin

      - name: Commit updated JSON files
        if: env.API_AVAILABLE == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add *.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update JSON data via KuCoin [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify API failure
        if: env.API_AVAILABLE == 'false'
        run: |
          echo "KuCoin API不可用，工作流终止"
          # 可以在这里添加通知逻辑，如Slack/webhook等