name: Daily AHR Execution

on:
  schedule:
    - cron: '30 00 * * *'
  workflow_dispatch: {}

jobs:
  run-ahr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          pip install pandas numpy scikit-learn python-binance python-dotenv

      - name: Run AHR Script
        run: |
          cd app/dashboard/python
          python ahr.py

      - name: Commit JSON Files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add app/dashboard/python/*.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update JSON data [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
